Implementing Disciplines
AreaFiftyLAN/toornament-client pull request #6
Opened 2017-05-20 23:59 UTC by Biokinetica

I hope these are the only three files that were necessary to commit.

2017-05-21 09:10 UTC, skamoen requested changes
You're missing the changes to ToornamentClient.java

Finally, the `TeamSize` private object in `DisciplineDetails` needs the full getter/setter/noargs constructor to work for Jackson. 

I found some other issues we'll deal with after the merge as they're important, but non-breaking and out of scope for this.

2017-05-21 09:10 UTC, skamoen commented on src/main/java/ch/wisv/toornament/concepts/Disciplines.java
> +        Request request = client.getAuthenticatedRequestBuilder().get().url("https://api.toornament.com/v1/disciplines"+ id ).build();
You're missing a `/` here.

You can also remove the TODO comments

2017-05-21 09:10 UTC, skamoen commented on src/main/java/ch/wisv/toornament/model/DisciplineDetails.java
>      @JsonProperty("additional_fields")
I ran into some trouble for this field, but that's because the Toornament API is very inconsistent here.

It's either a Map<Map<String, String>> or an empty array.
For example
```"additional_fields":{
    "faction":{
        "chimera":"Chimera",
        "usa":"United States Army",
        "cartel":"Cartel"
        }
    }
``` 
or `"additional_fields":[]`

You can fix this by adding this before the `return` statement of `getDiscipline(id)`
```
        mapper.configure(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true);
```
Furthermore, the additionalFields must be declared as 
```
    Map<String, Map<String, String>> additionalFields;
```

2017-05-21 09:10 UTC, skamoen commented on src/main/java/ch/wisv/toornament/concepts/Disciplines.java
> +        return mapper.readValue(responseBody, mapper.getTypeFactory().constructType(DisciplineDetails.class));
Add `mapper.configure(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true);` before this line to deal with empty additional_fields.

2017-05-21 13:03 UTC, Biokinetica commented on src/main/java/ch/wisv/toornament/concepts/Disciplines.java
> +        Request request = client.getAuthenticatedRequestBuilder().get().url("https://api.toornament.com/v1/disciplines"+ id ).build();
I'm not sure how Jackson works, so I don't know how this should be done. I'm guessing the below, but won't commit it for now.
```
private class TeamSize {
        int min;
        int max;
        public TeamSize(){
            
        }
        public int getMin(){
            return this.min;
        }
        public int getMax(){
            return this.max;
        }
        
    }
```

2017-05-21 13:25 UTC, Biokinetica commented
I was having issues committing after the pull request, but I think it's resolved now. I don't quite understand how this merging is being handled. This is the first project I've committed to that wasn't my own.

2017-05-25 09:54 UTC, skamoen commented
Now your file diffs are pretty messy again. It probably has to do with line endings, but in git-terms, you're overwriting the entire file instead of making small changes to it. This way it's very hard to track actual changes. For this reason I don't really want to merge this PR in the current form. Please try and make PR that only makes the actual changes you're making, instead of file overwrites.

2017-05-25 13:59 UTC, Biokinetica commented
I don't see why it's such a big deal when it's obvious what's been changed.

2017-05-25 14:07 UTC, skamoen commented on src/main/java/ch/wisv/toornament/ToornamentClient.java
> -    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
Because you miss stuff like this...

2017-05-25 15:25 UTC, Biokinetica commented on src/main/java/ch/wisv/toornament/ToornamentClient.java
> -    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
Then we can just add that line back in. This is a lot of jumping through hoops for something very minor.

2017-05-25 19:40 UTC, skamoen commented
Clean diffs are good and common practice for git repo's where multiple people collaborate. But I guess you're right it doesn't have to be perfect for something like this. If you can fix that line and double check if there's anything else we've missed, I'll merge it 😄

2017-06-23 09:29 UTC, Biokinetica commented
Ok, sorry about the wait; I added that last line. I've been busy applying for jobs and this fell to the back of the queue.

2017-07-01 09:13 UTC, merged